# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d16e2470ff4e34df0685515a4d8977533bb78eba9bf1d61aa9e2b745b8bc30f7655026c710091a5dfe5cc4be9d93ef60d1ed3423777227a8defb46d36bffea7

test:
  secret_key_base: ea049c92b0402945c6d364788d356680a88466bb6f021f95b22fb2a7c031686dc36b3d8177e898c0f79e47d29f5b8c0c32c3afa704855a23ff88c3e4904ac258

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
